// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKUo3ZdNOMKqdRJJ6Zc2sNOfB08krpnGQ',
    appId: '1:372132603269:web:d7e63bf5a45c44781d50ec',
    messagingSenderId: '372132603269',
    projectId: 'chat-app-2-22738',
    authDomain: 'chat-app-2-22738.firebaseapp.com',
    storageBucket: 'chat-app-2-22738.appspot.com',
    measurementId: 'G-NNQ90KJJTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsKRrAneQdBFb2JQc1f0Vuoaqxl3Dwlrg',
    appId: '1:372132603269:android:fa2bcb84791433b51d50ec',
    messagingSenderId: '372132603269',
    projectId: 'chat-app-2-22738',
    storageBucket: 'chat-app-2-22738.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcUm_bl0gRfgKxwF1JxSKwQe3qvqohZZY',
    appId: '1:372132603269:ios:813f66176d1ccab61d50ec',
    messagingSenderId: '372132603269',
    projectId: 'chat-app-2-22738',
    storageBucket: 'chat-app-2-22738.appspot.com',
    iosBundleId: 'com.example.chatapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcUm_bl0gRfgKxwF1JxSKwQe3qvqohZZY',
    appId: '1:372132603269:ios:c1747476646828e01d50ec',
    messagingSenderId: '372132603269',
    projectId: 'chat-app-2-22738',
    storageBucket: 'chat-app-2-22738.appspot.com',
    iosBundleId: 'com.example.chatapp2.RunnerTests',
  );
}
